add deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,7 +9,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Create .env file
+      - name: Créer fichier .env
         run: |
           echo "MYSQL_HOST=localhost" >> .env
           echo "MONGODB_HOST=localhost" >> .env
@@ -17,16 +17,16 @@ jobs:
           echo "DB_USERNAME=user" >> .env
           echo "DB_PASSWORD=pass" >> .env
 
-      - name: Install dependencies
+      - name: Installer les dépendances Python
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install pytest
 
-      - name: Start services
+      - name: Démarrer conteneur de test
         run: docker compose up -d
 
-      - name: Wait for MySQL
+      - name: Attendre l'initialisation du MySQL
         run: |
           sleep 10
           timeout=60
@@ -41,9 +41,35 @@ jobs:
           done
           sleep 5
 
-      - name: Run tests
+      - name: Exécuter les tests
         working-directory: src
         run: python3 -m pytest tests/test_user.py -v
+
+      - name: Déploiement via SSH
+        run: |
+          # Install SSH client
+          sudo apt-get update && sudo apt-get install -y openssh-client
+
+          if [ -z "${{ secrets.SSH_SERVER_HOST }}" ]; then
+            echo "ERROR: SSH_SERVER_HOST secret is not set or empty"
+            exit 1
+          else
+            echo "SSH_SERVER_HOST is set"
+          fi
+          
+          # Setup SSH key
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          
+          # Add server to known hosts to avoid host key verification prompt
+          ssh-keyscan -H ${{ secrets.SSH_SERVER_HOST }} >> ~/.ssh/known_hosts
+          
+          # Deploy via SSH
+          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }} << 'EOF'
+            cd log430-a25-labo0
+            git pull origin main
+          EOF
 
       - name: Cleanup
         if: always()
